apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: update-controller
  namespace: udl
spec:
  chartRef:
    kind: OCIRepository
    name: update-controller
    namespace: udl
  interval: 10m
  values:
    config:
      podSelector: "update=udl"
      namespace: "udl"
    namespace:
      create: false
