apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fastdl
  namespace: udl
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fastdl.udl.tf`)
      kind: Rule
      services:
        - name: fastdl
          port: 80
