apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.helmrelease.yaml
- cert-manager.helmrepository.yaml
- external-secrets.helmrelease.yaml
- external-secrets.helmrepository.yaml
- gotk-components.yaml
- gotk-sync.yaml
- kubernetes-replicator.helmrelease.yaml
- kubernetes-replicator.helmrepository.yaml
- sealed-secrets.helmrelease.yaml
- sealed-secrets.helmrepository.yaml
